### ISSUE TITLE
Add the ability to mark trails as hiked

### ISSUE THREAD

**Issue by oliverzheng** [shuw/trails#1]
Gotta catch'em all.

**Comment by oliverzheng** [comment]
@shuw, do you have a preference for how you want this done? For starters, some simple client-side local storage way of marking it? I kind of really want this.

**Comment by shuw** [comment]
First, there needs to be FB login integration. then you can store the state against that account (maybe Parse)? I don't trust the DB on my free Heroku database.

Then, add the ability to share your hikes on FB, and earn awards for reaching some milestones.

**Comment by oliverzheng** [comment]
To make it simple for a first step, would you be okay with storing this locally in local storage so there's no login integration or server component? They won't roam across devices/browsers, but we can add a text blurb about the limitation.

**Comment by shuw** [comment]
Sure, you can mark all the visited trails in a special color. And add a profile with some interesting stats such as: miles hiked, elevation gained, etc (based on the history)

But I think this feature really needs persistence to be useful. But having the UI built out is a good first step.

**Comment by shuw** [comment]
deployed to http://www.gointothewoods.com/
